var annotated_dup =
[
    [ "AccessClient", "classAccessClient.html", "classAccessClient" ],
    [ "AliveGuard", "classAliveGuard.html", "classAliveGuard" ],
    [ "AliveState", "classAliveState.html", "classAliveState" ],
    [ "BaudRate", "classBaudRate.html", "classBaudRate" ],
    [ "ClientAcceptor", "classClientAcceptor.html", "classClientAcceptor" ],
    [ "ClientHandler", "classClientHandler.html", "classClientHandler" ],
    [ "ClientHandlerCollection", "classClientHandlerCollection.html", "classClientHandlerCollection" ],
    [ "DataSource", "classDataSource.html", "classDataSource" ],
    [ "FlowGuard", "classFlowGuard.html", "classFlowGuard" ],
    [ "Frame", "classFrame.html", "classFrame" ],
    [ "FrameGenerator", "classFrameGenerator.html", "classFrameGenerator" ],
    [ "FrameParser", "classFrameParser.html", "classFrameParser" ],
    [ "ISerialPortHandler", "classISerialPortHandler.html", "classISerialPortHandler" ],
    [ "LineReader", "classLineReader.html", "classLineReader" ],
    [ "LockGuard", "classLockGuard.html", "classLockGuard" ],
    [ "Packet", "classPacket.html", "classPacket" ],
    [ "PacketCtrl", "classPacketCtrl.html", "classPacketCtrl" ],
    [ "PacketData", "classPacketData.html", "classPacketData" ],
    [ "PacketEndpoint", "classPacketEndpoint.html", "classPacketEndpoint" ],
    [ "ProtocolState", "classProtocolState.html", "classProtocolState" ],
    [ "SerialPortHandler", "classSerialPortHandler.html", "classSerialPortHandler" ],
    [ "SerialPortHandlerCollection", "classSerialPortHandlerCollection.html", "classSerialPortHandlerCollection" ],
    [ "SerialPortLock", "classSerialPortLock.html", "classSerialPortLock" ],
    [ "Statistic", "classStatistic.html", "classStatistic" ]
];