var annotated_dup =
[
    [ "AliveGuard", "classAliveGuard.html", "classAliveGuard" ],
    [ "AliveState", "classAliveState.html", "classAliveState" ],
    [ "BaudRate", "classBaudRate.html", "classBaudRate" ],
    [ "Frame", "classFrame.html", "classFrame" ],
    [ "FrameEndpoint", "classFrameEndpoint.html", "classFrameEndpoint" ],
    [ "FrameGenerator", "classFrameGenerator.html", null ],
    [ "FrameParser", "classFrameParser.html", "classFrameParser" ],
    [ "HdlcdClient", "classHdlcdClient.html", "classHdlcdClient" ],
    [ "HdlcdPacket", "classHdlcdPacket.html", "classHdlcdPacket" ],
    [ "HdlcdPacketCtrl", "classHdlcdPacketCtrl.html", "classHdlcdPacketCtrl" ],
    [ "HdlcdPacketData", "classHdlcdPacketData.html", "classHdlcdPacketData" ],
    [ "HdlcdPacketEndpoint", "classHdlcdPacketEndpoint.html", "classHdlcdPacketEndpoint" ],
    [ "HdlcdServerHandler", "classHdlcdServerHandler.html", "classHdlcdServerHandler" ],
    [ "HdlcdServerHandlerCollection", "classHdlcdServerHandlerCollection.html", "classHdlcdServerHandlerCollection" ],
    [ "HdlcdSessionDescriptor", "classHdlcdSessionDescriptor.html", "classHdlcdSessionDescriptor" ],
    [ "HdlcdSessionHeader", "classHdlcdSessionHeader.html", "classHdlcdSessionHeader" ],
    [ "HdlcFrame", "classHdlcFrame.html", "classHdlcFrame" ],
    [ "ISerialPortHandler", "classISerialPortHandler.html", "classISerialPortHandler" ],
    [ "LockGuard", "classLockGuard.html", "classLockGuard" ],
    [ "ProtocolState", "classProtocolState.html", "classProtocolState" ],
    [ "SerialPortHandler", "classSerialPortHandler.html", "classSerialPortHandler" ],
    [ "SerialPortHandlerCollection", "classSerialPortHandlerCollection.html", "classSerialPortHandlerCollection" ],
    [ "SerialPortLock", "classSerialPortLock.html", "classSerialPortLock" ]
];